Use toasts instead of alert for errors
Rari-Capital/rari-dApp pull request #163
Opened 2020-10-23 17:51 UTC by Yashs911

Fixes #159

2020-10-23 17:59 UTC, TransmissionsDev commented
Hey @Yashs911, thank you so much for your PR!

However, the `toast` function takes an object with more info about how to render the toast (more info here: https://chakra-ui.com/toast)

Your PR calls `toast(e)` which will not work, please make another commit that calls toast like this:

```
toast({
          title: "Error!",
          description: e.toString(),
          status: "error",
          duration: 9000,
          isClosable: true,
})
```

2020-10-23 18:04 UTC, TransmissionsDev commented on src/components/pages/DepositModal/AmountSelect.tsx
> +        toast(e);
```
toast({
          title: "Error!",
          description: e.toString(),
          status: "error",
          duration: 9000,
          isClosable: true,
})
```

2020-10-23 18:04 UTC, TransmissionsDev commented on src/components/pages/DepositModal/AmountSelect.tsx
> +        toast(e);
```
toast({
          title: "Error!",
          description: e.toString(),
          status: "error",
          duration: 9000,
          isClosable: true,
})
```

2020-10-23 18:05 UTC, TransmissionsDev requested changes
Follow my comments and then I will happily merge this 👍

2020-10-24 05:45 UTC, Yashs911 commented on src/components/pages/DepositModal/AmountSelect.tsx
> +        toast(e);
Okay

2020-10-24 07:02 UTC, TransmissionsDev requested changes
Just need two semicolons and I will merge this!

2020-10-24 07:02 UTC, TransmissionsDev commented on src/components/pages/DepositModal/AmountSelect.tsx
> +        })
Can you add a semicolon here?

2020-10-24 07:02 UTC, TransmissionsDev commented on src/components/pages/DepositModal/AmountSelect.tsx
> +        })
Please add a semicolon here 👍

2020-10-24 07:07 UTC, TransmissionsDev approved these changes

2020-10-24 07:07 UTC, TransmissionsDev commented
Nevermind, no point in being this picky, mering now thank you very much for your help!

2020-10-24 07:07 UTC, merged